# Generated by Django 4.1.2 on 2022-10-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default=123, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
